---
# wholesale test double injection
# this one uses http template fetching
# broccoli build one to come

# ember.data.adapter:
#   arguments:
#     finder: "@service:finder.double.fetch"

# double injection for a single route
# app.datacenter.adapter:
#   class: "adapter:datacenter"
#   arguments:
#     finder: "@service:finder.double.fetch"

# app.data.service:
#   object: "@service:store"
